'use server';

import { revalidatePath } from 'next/cache';
import { redirect } from 'next/navigation';
import { createClient, createAdminClient } from '@/lib/supabase/server';
import { sendInvitationEmail } from '@/lib/email/resend';
import type { ActionResult, Permission } from '@lore/shared';

export async function sendInvitation(
  campaignId: string,
  formData: FormData
): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const email = (formData.get('email') as string)?.toLowerCase().trim();
  const permission = formData.get('permission') as Permission;

  if (!email) return { error: 'Email is required' };
  if (!['read', 'write'].includes(permission)) return { error: 'Invalid permission' };

  const adminClient = createAdminClient();

  // Verify caller is campaign owner and fetch campaign name + inviter display name
  const [{ data: campaign }, { data: profile }] = await Promise.all([
    adminClient
      .from('campaigns')
      .select('id, name, owner_id')
      .eq('id', campaignId)
      .eq('owner_id', user.id)
      .single(),
    adminClient
      .from('profiles')
      .select('display_name')
      .eq('id', user.id)
      .single(),
  ]);

  if (!campaign) return { error: 'Campaign not found or access denied' };

  // Create invitation — token is generated by DB default
  const { data: invitation, error: invError } = await adminClient
    .from('campaign_invitations')
    .insert({
      campaign_id: campaignId,
      invited_by: user.id,
      email,
      permission,
    })
    .select('token')
    .single();

  if (invError) {
    if (invError.code === '23505') return { error: 'An invitation for this email already exists' };
    return { error: invError.message };
  }

  const inviteUrl = `${process.env.NEXT_PUBLIC_APP_URL}/invite/${invitation.token}`;

  try {
    await sendInvitationEmail({
      to: email,
      campaignName: campaign.name,
      inviterName: profile?.display_name ?? 'Your Dungeon Master',
      inviteUrl,
      permission,
    });
  } catch {
    // Email failure should not roll back the invitation — DM can still share the link
    console.error('Failed to send invitation email for token:', invitation.token);
  }

  revalidatePath(`/campaigns/${campaignId}/members`);
  return {};
}

export async function acceptInvitation(token: string): Promise<ActionResult<string>> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const adminClient = createAdminClient();
  const { data: campaignId, error } = await adminClient.rpc('accept_campaign_invitation', {
    p_token: token,
    p_user_id: user.id,
  });

  if (error) return { error: error.message };

  revalidatePath('/campaigns');
  redirect(`/campaigns/${campaignId}`);
}

export async function revokeInvitation(
  invitationId: string,
  campaignId: string
): Promise<ActionResult> {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: 'Not authenticated' };

  const adminClient = createAdminClient();

  // Verify the invitation belongs to a campaign owned by the current user
  const { data: invitation } = await adminClient
    .from('campaign_invitations')
    .select('campaign_id')
    .eq('id', invitationId)
    .single();

  if (!invitation) return { error: 'Invitation not found' };

  const { data: campaign } = await adminClient
    .from('campaigns')
    .select('id')
    .eq('id', invitation.campaign_id)
    .eq('owner_id', user.id)
    .single();

  if (!campaign) return { error: 'Access denied' };

  const { error } = await adminClient
    .from('campaign_invitations')
    .delete()
    .eq('id', invitationId);

  if (error) return { error: error.message };

  revalidatePath(`/campaigns/${campaignId}/members`);
  return {};
}
