-- Migration 010: Video Pipeline V2
-- Adds image_url (keyframe thumbnail) and fal_model (which fal.ai model was used)
-- to the videos table.

ALTER TABLE videos
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS fal_model TEXT NOT NULL DEFAULT 'fal-ai/kling-video/v1.6/standard/text-to-video';

COMMENT ON COLUMN videos.image_url IS 'Permanent Supabase CDN URL for the scene keyframe image generated by FLUX dev. NULL for videos created before this migration.';
COMMENT ON COLUMN videos.fal_model IS 'The fal.ai model path used to generate this video. Used by the status polling endpoint to check the correct queue.';
